name: deploy-on-push-and-schedule

on:
  push:
  schedule:
    - cron:  '0 17 * * *'

jobs:
  build:
    runs-on: ubuntu-18.04
    if: "!contains(github.event.head_commit.message, 'ci-skip')"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@master
      - name: Query dependencies
        run: |
          Rscript \
            -e "install.packages('remotes')" \
            -e "saveRDS(remotes::dev_package_deps(dependencies = TRUE), 'depends.Rds', version = 2)"
      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('depends.Rds') }}
          restore-keys: ${{ runner.os }}-r
      - name: Install system dependencies
        env:
          RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
        run: |
          Rscript -e "remotes::install_github('r-hub/sysreqs')"
          sysreqs=$(Rscript -e "cat(sysreqs::sysreq_commands('DESCRIPTION'))")
          sudo -s eval "$sysreqs"
      - name: Install dependencies
        run: |
          Rscript \
            -e "library(remotes)" \
            -e "update(readRDS('depends.Rds'))"
      - name: Run Script For Pre-workshop survey
        run: |
          Rscript \
            -e "source('archive-typeform.R')" \
            -e "cache_content(get_form('wi32rS'), 'pre-workshop')"
      - name: Run Script for Post-workshop survey
        run: |
          Rscript \
            -e "source('archive-typeform.R')" \
            -e  "cache_content(get_form('UgVdRQ'), 'post-workshop')"
      - name: Move files to public folder for deployment
        run: |
          Rscript \
          -e "source('build-website.R')" \
          -e "generate_archive_website()"
      - name: Deploy to ghpages
        if: github.ref == 'refs/heads/master'
        uses: maxheld83/ghpages@v0.2.1
        env:
           BUILD_DIR: public
           GH_PAT: ${{ secrets.GH_PAT }}
      - name: Commit files to master
        run: |
          rm -rf public/
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add *
          git commit -m "[ci-skip] add latest version"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
